### PR TITLE
Power pcb

### PR DESCRIPTION
**Pull request by NChitty**

### CODE REVIEW

**Comment by myhe01** [comment]
> but one thing you need to go in and do is make sure the SMD pads AND vias are connected to the right nets, and you also need to delete any leftover tracks hiding in the SMD pads because they're giving you DRC errors

> if you can stomach it, i'd recommend making VBAT a power plane on the 3rd layer instead of a pour in the middle

**Comment by myhe01** [comment]
Minimum annular ring DRC violation (<5.118mil) on 15/25mil vias.

**Comment by myhe01** [comment]
Silk to solder mask DRC errors.

**Comment by myhe01** [comment]
[Design Rule Verification Report.pdf](https://github.com/SeniorDesign-Group9/pcb/files/10805807/Design.Rule.Verification.Report.pdf)

**Comment by NChitty** [comment]
[Design Rule Verification Report.pdf](https://github.com/SeniorDesign-Group9/pcb/files/10809500/Design.Rule.Verification.Report.pdf)

**Review by myhe01 — CHANGES_REQUESTED** [review]
**Request changes:**
Please make sure there's still solder pads on the ground pins of J1.
image

Can we add a silk of the board name like shown below? Also, you can specify where JLCPCB puts the order number so you don't have to pay extra to have it removed (also shown below, the backwards "JLCJLCJLCJLC").
image

**Comments:**
It's possible to change test points to only be on one side so that way there isn't exposed copper on the bottom of the board. Just change it from Multi-Layer to the layer you want.
image

**Review by myhe01 — APPROVED** [review]
Send it

**Pull request merged**
